experiment:
  run_name: "inference-setting-1"

shared:
  sample_rate: 24000
  input_sec: 2.56
  time_res: 0.01
  win_length: 2048

model:
  enc_layers: 4
  dec_layers: 4
  d_query: 128
  dropout: 0.1

tokenizer:
  ADTOF_mapping: true
  BOS_token: 2
  EOS_token: 3
  pad_token: 1
  silence_token: 0
  add_velocity: true

EvalDatasetConfig:
  dataset_path: "path_to_dataset"
  drummers: null
  dataset_name: "ENST"
  minus_one: true
  splits: [2]

inference:
  checkpoint_path: "path_to_checkpoint"
  batch_size: 1
  max_length: 1000
  beam_size: 5
  use_beam_search: false
  instrument: "drums"
  max_samples: 4096
  output_path: "path_to_output"

logging:
  log_level: "INFO"
