experiment:
  run_name: "inference-MDB-TMIDT"

shared:
  sample_rate: 24000

model:
  enc_layers: 4
  dec_layers: 4
  d_query: 128
  dropout: 0.1

tokenizer:
  ADTOF_mapping: true
  BOS_token: 2
  EOS_token: 3
  pad_token: 1
  silence_token: 0
  add_velocity: false

EvalDatasetConfig:
  dataset_path: "/home/ec2-user/data/parquet/MDB/data@24000/0000.parquet"
  dataset_name: "MDB"
  demucs_separated: false
  splits: null


inference:
  checkpoint_path: "/home/ec2-user/ADT_STR/outputs/TMIDT"
  batch_size: 1
  max_length: 1000
  beam_size: 5
  use_beam_search: false
  instrument: "drums"
  max_samples: 4096
  output_path: "/home/ec2-user/ADT_STR/results/TMIDT/MDB_inference/"

logging:
  log_level: "INFO"
