shared:
  input_sec: 2.56
  time_res: 0.01
  win_length: 2048
  sample_rate: 44100

EvalDataPreprocess:
  dataset_path: "path_to_dataset"
  drummers: null
  output_path: "path_to_output"
  dataset_name: "ENST"

EvalDatasetConfig:
  dataset_path: "path_to_dataset"
  drummers: null
  dataset_name: "ENST"
  minus_one: true