shared:
  input_sec: 2.56
  time_res: 0.01
  win_length: 2048
  sample_rate: 24000

EvalDataPreprocess:
  dataset_path: "/home/ec2-user/data/MDB"
  output_path: "/home/ec2-user/data/parquet/"
  dataset_name: "MDB"
  audio_extension: "wav"

EvalDatasetConfig:
  dataset_path: "/home/ec2-user/data/parquet/"
  dataset_name: "MDB"
  demucs_separated: true
  splits: null

tokenizer:
  ADTOF_mapping: true
  BOS_token: 2
  EOS_token: 3
  pad_token: 1
  silence_token: 0