shared:
  input_sec: 2.56
  time_res: 0.01
  win_length: 2048
  sample_rate: 24000

EvalDataPreprocess:
  dataset_path: "/workspace/data/midi"
  output_path: "/workspace/data"
  dataset_name: "TMIDT"
  audio_extension: "mp3"
  dataset_size: "m"
  drums_only: true
  num_audio_files: 1500